### ISSUE TITLE
v1.0.1 disconnects in CuteChess

### ISSUE THREAD

**Issue by tissatussa** [JoostHouben/Euwe-chess-engine#2]
this happens suddenly, but every game - sometimes at move 15, sometimes at move 4 - see also [#1]
i let it play 4 games 5m+3s, this was the first one :

```
[Event "engine vs engine"]
[Site "Holland"]
[Date "2024.08.17"]
[Round "?"]
[White "Euwe v1.0.1"]
[Black "4KU v5.0"]
[Result "0-1"]
[FEN "rnbqkbnr/ppp1pppp/8/4N3/4P3/3p4/PPPP1PPP/RNBQKB1R w KQkq - 0 4"]
[GameDuration "00:05:59"]
[PlyCount "30"]
[SetUp "1"]
[Termination "abandoned"]
[TimeControl "300+3"]

1. Bxd3 {+1.00/9 11s} Nd7 {-1.37/25 14s} 2. Nxd7 {+0.98/10 11s}
Bxd7 {-1.33/26 11s} 3. Nc3 {+0.91/10 11s} e5 {-1.12/25 10s}
4. Qh5 {+0.92/11 11s} Qe7 {-1.19/24 10s} 5. Nd5 {+0.81/11 11s}
Nf6 {-1.09/30 10s} 6. Nxe7 {+0.78/12 11s} Nxh5 {-0.94/31 14s}
7. Nd5 {+0.84/11 11s} Rc8 {-1.11/26 8.8s} 8. g3 {+0.83/10 11s}
Be6 {-1.12/25 9.4s} 9. O-O {+0.87/9 11s} c6 {-1.28/24 8.3s}
10. Ne3 {+0.91/11 11s} Nf6 {-1.34/26 30s} 11. b3 {+0.90/11 11s}
Rd8 {-1.29/26 8.0s} 12. Bb2 {+0.94/11 11s} Nd7 {-1.44/25 13s}
13. Rfd1 {+0.88/10 11s} Nc5 {-1.30/26 7.0s} 14. Be2 {+0.90/10 11s}
Nxe4 {-1.39/27 7.5s} 15. d3 {+0.94/11 11s} Nf6 {-1.38/27 25s, White disconnects}
0-1
```

ZIPped CuteChess log pane output : [euwe-v1-0-1-disconnect-cutechess-log.zip](https://github.com/user-attachments/files/16646273/euwe-v1-0-1-disconnect-cutechess-log.zip)

CuteChess can also log to `stderr`. I didn't find a way in CuteChess GUI (v1.3.1) to set the `stderrFile` path but this can be done by hand in ~/.config/cutechess.json for each configured engine. Here also your [DEBUG] messages are logged.

This was the log tail of the messages in `stderrFile` :

```
euwe-engine-v1.0.1-compiled-HP-commit-6f51934: chess-engine-lib/GameState.cpp:689: Piece GameState::makeSinglePieceMove(const Move&): Assertion `move.to == enPassantTarget_' failed.
```

**Comment by JoostHouben** [comment]
Thanks for reporting!

I hadn't ran a full game in debug mode in a while. Clearly some bugs snuck in which the debug checks were able to catch.

I think I found and fixed the relevant issues. I ran ~150 games between two copies of the latest version of the code built in debug mode, and no crashes or other issues occurred.

Let me know if the issue is fixed on the latest revision!

**Comment by tissatussa** [comment]
All went well (a few adjustments aside).
I will close this Issue now.
