### ISSUE TITLE
Custom build : use Meson

### ISSUE THREAD

**Issue by tissatussa** [JoostHouben/Euwe-chess-engine#3]
To compile your sources on Linux, i managed to create a `Makefile` which uses gcc-14.2.0, see my #1 and #2 .
Today i discovered the Meson build system, like cmake and make, and it seems promising.
However, i think the documentation is poor, although https://mesonbuild.com seems to have all info; i found most options and arguments in reviews and forum entries.

See the fixed (for my Linux) and repacked version here : [Euwe-chess-engine-v1.1.0-fixed-code-with-own-Mason-build.zip](https://github.com/user-attachments/files/16648349/Euwe-chess-engine-v1.1.0-fixed-code-with-own-Mason-build.zip)

It should also compile on Windows with little Meson file adjustments, see my INSTALL.txt

I changed a few things.

- all code files `.cpp` and `.h` are now in `src/`, AFAIK Meson demands it ?
- in `UciFrontEnd.cpp` i (still) had to replace `std::round()` by just `round()` and add `#include <cmath>` on top.
- in `Main.cpp` (in src/) i removed the include paths.
- in `Intrinsics.h` i added `#include <immintrin.h>` on top, see comments in file. Btw. you had `#include "immintrin.h"` which means some own header file to me, but you did't supply it. The OS seems to find it in both cases !?

AVX and BMI are autodetected and set.
Yet i found no other way but running meson by its Python file, maybe this is common ?
More info about my Meson setup : see comments in the mentioned files.

My v1.1.0 binary is 475 Kb in size and gives no errors in CuteChess GUI.

( now i will try to use Meson for other C packages and learn ! )

**Comment by tissatussa** [comment]
I was wondering how to `include directories` and upto now i failed, that's why i put all code files in `src/`. I just found [Unable to specify multiple things using include_directories](https://github.com/mesonbuild/meson/issues/2124) and it reveals some new (to me) options and constructs, they can be helpful. Also look at the `colord` module, mentioned at the end, it uses the Meson build system.

And .. i also found [Adding library and include directory](https://github.com/mesonbuild/meson/issues/11570) which shows not all is clear with Meson ..

**Comment by tissatussa** [comment]
Still learning about Meson, can't figure out how to add the right `meson.build` files into (each?) folder, so with your newest v1.2.0 i rearranged the code files again and compiling went well, despite those few changes i must edit. Congrats with the new version !

But why you chose to have 2 folders `chess-engine` and `chess-engine-lib`, the first having only one file ? Why not just one `src/` folder ?

**Comment by tissatussa** [comment]
i think i figured it out .. it's simple and the 'Meson Way' : [meson-build-files-wo-googletest.zip](https://github.com/user-attachments/files/16710392/meson-build-files-wo-googletest.zip)
put the 2 mason files in the root of your project and follow the steps in my INSTALL.txt

**Comment by JoostHouben** [comment]
As of version 1.3, Linux is officially supported. The build configuration is now based on CMake and vcpkg. The release for version 1.3 includes pre-built linux binaries.
